# after https://github.com/reckenrode/nixos-configs/blob/f61d83e56ed7569c31ca67591bcf7856f1b8ac4a/.github/workflows/main.yml
name: Bump flake.lock

# Manually
on: workflow_dispatch
#  schedule:
#    - cron: "0 6 * * *"


jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: cachix/install-nix-action@v20
      - run: nix flake update

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump flake.lock
          branch: main
          commit_options: '--no-verify --signoff'
          file_pattern: flake.lock
          commit_user_name: FlakeBot
          commit_author: FlakeBot <actions@github.com>
          skip_dirty_check: false
          skip_fetch: true